server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    database: mysql
    show-sql: true
    open-in-view: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadme?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

logging:
  level:
    org.hibernate.type: trace
    com.ssafy.withme: debug

kakao:
  client:
    id: 906844f5e157bcb88f914f692843c753